//
// Created by User on 5/30/2022.
//

#ifndef SYMBOLTABLEMANAGER_H_SCOPETYPE_H
#define SYMBOLTABLEMANAGER_H_SCOPETYPE_H

enum ScopeType{WHILE_SCOPE, FUNC_SCOPE, OTHER_SCOPE};

#endif //SYMBOLTABLEMANAGER_H_SCOPETYPE_H
