//
// Created by User on 5/29/2022.
//

#ifndef SYMBOLTABLEMANAGER_CPP_TYPE__H
#define SYMBOLTABLEMANAGER_CPP_TYPE__H

enum Type_{TYPE_STRING, TYPE_INT, TYPE_VOID, TYPE_NOT_VALID};

#endif //SYMBOLTABLEMANAGER_CPP_TYPE__H
